query OrdersQuery($org_id: String!, $city: String!, $delivered_date: String!, $ordered_date: String!, $point_of_contact: String!) {
  pointOfContactDetailedReport(object: {city: $city, delivered_date: $delivered_date, ordered_date: $ordered_date, org_id: $org_id, point_of_contact: $point_of_contact}) {
    data {
      city
      actual_delivery_date
      app_order_code
      backend_order_status
      customer_name
      delivery_slot
      erp_order_code
      erp_order_status
      first_name
      last_name
      order_amount
      order_delivered_qty
      order_date
      order_qty
      phone_number
      shipping_address
    }
  }
}