query OrdersQuery($org_id: String!, $city: String!, $delivery_date_from: String!, $delivery_date_to: String!, $order_date_from: String!, $order_date_to: String!, $point_of_contact: String!) {
  pointOfContactDetailedReport(object: {org_id: $org_id, city: $city, delivery_date_from: $delivery_date_from, delivery_date_to: $delivery_date_to, order_date_from: $order_date_from, order_date_to: $order_date_to, point_of_contact: $point_of_contact}) {
    data {
      actual_delivery_date
      app_order_code
      backend_order_status
      city
      customer_name
      delivery_slot
      erp_order_code
      erp_order_status
      first_name
      last_name
      order_amount
      order_date
      order_delivered_qty
      order_qty
      phone_number
      shipping_address
    }
  }
}