query DashboardQuery($org_id: String!, $city: String!, $delivery_date_to: String!, $delivery_date_from: String!, $order_date_from: String!, $order_date_to: String!, $point_of_contact: String!) {
  pointOfContactDashboard(object: {org_id: $org_id, city: $city, delivery_date_to: $delivery_date_to, delivery_date_from: $delivery_date_from, order_date_from: $order_date_from, order_date_to: $order_date_to, point_of_contact: $point_of_contact}) {
    data {
      cancelled_count
      cancelled_qty
      delivered_orders
      delivered_qty
      order_count
      ordered_qty
      planned_orders
      planned_qty
    }
  }
  pointOfContactDashboardReschedule(object: {org_id: $org_id, city: $city, delivery_date_from: $delivery_date_from, delivery_date_to: $delivery_date_to, order_date_from: $order_date_from, order_date_to: $order_date_to, point_of_contact: $point_of_contact}) {
    data {
      rescheduled_count
      rescheduled_qty
    }
  }
}