query InvoicesQuery($org_id: String!, $city: String!, $delivery_date_from: String!, $delivery_date_to: String!, $order_date_from: String!, $order_date_to: String!, $point_of_contact: String!) {
  pointOfContactInvoiceReport(object: {org_id: $org_id, city: $city, delivery_date_from: $delivery_date_from, delivery_date_to: $delivery_date_to, order_date_from: $order_date_from, order_date_to: $order_date_to, point_of_contact: $point_of_contact}) {
    data {
      app_order_code
      city
      delivered_date
      erp_order_code
      first_name
      invoice
      last_name
      order_amount
      order_date
      order_delivered_qty
      order_qty
      phone_number
      shipping_address
    }
  }
}